name: majik
version: 0.0.1
author: Name It Later
description: Virtual services inspired by SmartStack.
homepage: https://github.com/nameitlater/majik
environment:
  sdk: '>=1.4.3 <2.0.0'
dependencies:
  args: '>=0.10.0 < 0.11.0'
  mustache: '>=0.1.8 <0.1.9'
  eureka:
    git: https://github.com/nameitlater/eureka.git
dev_dependencies:
  unittest: '>=0.11.0 < 0.12.0'
